services:
  netalertx:
    image: ghcr.io/netalertx/netalertx:latest
    container_name: netalertx
    network_mode: host
    restart: unless-stopped

    cap_add:
      - NET_RAW
      - NET_ADMIN
      - NET_BIND_SERVICE
      - CHOWN
      - SETUID
      - SETGID

    volumes:
      - netalertx_data:/data
      - /etc/localtime:/etc/localtime:ro

    tmpfs:
      - /tmp:uid=20211,gid=20211,mode=1700

    environment:
      - PORT=20211
      - GRAPHQL_PORT=20214
      - APP_CONF_OVERRIDE={"GRAPHQL_PORT":"20214"}

volumes:
  netalertx_data: