services:
  proxy:
    image: zabbix/zabbix-proxy-sqlite3:alpine-7.4-latest
    container_name: zabbix-proxy
    restart: unless-stopped
    init: true
    environment:
      - ZBX_HOSTNAME={{ .hostname }}
      - ZBX_SERVER_HOST={{ .server_host }}
      - ZBX_TLSPSKIDENTITY={{ .tls_psk_identity }}
      - ZBX_TLSPSK={{ .tls_psk }}
      - ZBX_TLSCONNECT=psk